### YamlMime:QSharpType
uid: microsoft.quantum.canon.compose
name: Compose
type: function
namespace: microsoft.quantum.canon
summary: >-
  Vrátí kompozici dvou funkcí.


  Zadané dvě funkce $f $ a $g $, vrátí novou funkci reprezentující $f \circ g $.
syntax: "function Compose (outer : ('U -> 'V), inner : ('T -> 'U)) : ('T -> 'V)"
input:
  content: "(outer : ('U -> 'V), inner : ('T -> 'U))"
  types:
  - name: outer
    summary: Druhá funkce, která má být použita.
    isFunction: true
    input:
      types:
      - uid: "'U"
        isLocal: true
    output:
      types:
      - uid: "'V"
        isLocal: true
  - name: inner
    summary: První funkce, která se má použít
    isFunction: true
    input:
      types:
      - uid: "'T"
        isLocal: true
    output:
      types:
      - uid: "'U"
        isLocal: true
output:
  content: ('T -> 'V)
  types:
  - summary: Nová funkce $h $, což pro všechny vstupy $x $, $f (g (x)) = h (x) $.
    isFunction: true
    input:
      types:
      - uid: "'T"
        isLocal: true
    output:
      types:
      - uid: "'V"
        isLocal: true
typeParameters:
- uid: "'T"
  summary: Vstupní typ první funkce, která má být použita.
- uid: "'U"
  summary: Typ výstupu první funkce, která má být použita, a vstupní typ druhé funkce, která má být použita.
- uid: "'V"
  summary: Typ výstupu druhé funkce, která má být použita.
metadata:
  ms.openlocfilehash: e62937fd42cb4067ca7a7947cac29a9ef539da6c
  ms.sourcegitcommit: d6ac6f4345be0dd68f1bcd944f44b08e7a3cf346
  ms.translationtype: MT
  ms.contentlocale: cs-CZ
  ms.lasthandoff: 09/02/2020
  ms.locfileid: "89356741"
