### YamlMime:QSharpType
uid: microsoft.quantum.canon.decomposeintotimestepsca
name: DecomposeIntoTimeStepsCA
type: function
namespace: Microsoft.Quantum.Canon
summary: Vrátí operaci implementující integrátoru Trotter – Suzuki pro danou operaci.
syntax: "function DecomposeIntoTimeStepsCA ((nSteps : Int, op : ((Int, Double, 'T) => Unit is Adj + Ctl)), trotterOrder : Int) : ((Double, 'T) => Unit is Adj + Ctl)"
references: >-
  We use the implementation in


  - [ *D. W. Berry, G. Ahokas, R. Cleve, B. C. Sanders* ](https://arxiv.org/abs/quant-ph/0508139)
input:
  content: '((nSteps: int, op: ((int, Double, t) = > jednotka je ADJ + CTL)), trotterOrder: int)'
  types:
  - name: nSteps
    isPrimitive: true
    uid: Int
  - name: evřít
    isOperation: true
    input:
      types:
      - isPrimitive: true
        uid: Int
      - isPrimitive: true
        uid: Double
      - uid: "'T"
        isLocal: true
    output:
      types:
      - isPrimitive: true
        uid: Unit
    functors:
    - Adjoint
    - Controlled
  - name: trotterOrder
    summary: >-
      Vybere pořadí, ve kterém se má použít integrátor Trotter-Suzuki.

      Pořadí 1 a 2 jsou aktuálně podporovány.
    isPrimitive: true
    uid: Int
output:
  content: ((Double, t) = > jednotka je ADJ + CTL)
  types:
  - summary: Vrátí jednotnou implementaci integrátoru Trotter – Suzuki, kde první parametr `Double` je velikost kroku integrace a druhý parametr je cílem, na kterém se pracuje.
    isOperation: true
    input:
      types:
      - isPrimitive: true
        uid: Double
      - uid: "'T"
        isLocal: true
    output:
      types:
      - isPrimitive: true
        uid: Unit
    functors:
    - Adjoint
    - Controlled
typeParameters:
- uid: "'T"
  summary: Typ, na který má každý krok reagovat; obvykle buď `Qubit[]`, nebo `Qubit`.
ms.openlocfilehash: 328db9b314320c724cf03adb19ee59d63a33e56e
ms.sourcegitcommit: 8becfb03eb60ba205c670a634ff4daa8071bcd06
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 10/30/2019
ms.locfileid: "73067828"
