### YamlMime:QSharpNamespace
uid: microsoft.quantum.environment
name: Microsoft.Quantum.Environment
summary: " # <a name=\"summary\"></a>Souhrn\n Tyto funkce poskytují informace o prostředí, ve kterém dochází k výpočtu doby."
operations:
- uid: microsoft.quantum.environment.getqubitsavailabletoborrow
  summary: >-
    Vrátí počet qubitsů, které jsou aktuálně k dispozici k vypůjčení.

    To zahrnuje nepoužívané qubits; To znamená, že zahrnuje qubits vrácené funkcí `GetQubitsAvailableToUse`.
- uid: microsoft.quantum.environment.getqubitsavailabletouse
  summary: Vrátí počet qubits aktuálně dostupných k použití.
metadata:
  ms.openlocfilehash: 50e5cfb7c1b9a4075c25b2705d00b435a09e159e
  ms.sourcegitcommit: edcf15044d7bdf4f8b21fb8f6af4bde475eb13a0
  ms.translationtype: MT
  ms.contentlocale: cs-CZ
  ms.lasthandoff: 11/05/2019
  ms.locfileid: "73056832"
