### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletoborrow
name: GetQubitsAvailableToBorrow
type: operation
namespace: Microsoft.Quantum.Environment
summary: >-
  Vrátí počet qubitsů, které jsou aktuálně k dispozici k vypůjčení.

  To zahrnuje nepoužívané qubits; To znamená, že zahrnuje qubits vrácené funkcí `GetQubitsAvailableToUse`.
syntax: 'operation GetQubitsAvailableToBorrow () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      Počet qubits, které mohou být přiděleny v příkazu `borrowing`.

      Pokud použitý cílový počítač tyto informace neposkytuje, vrátí se `-1`.
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletouse
ms.openlocfilehash: c0caf866ad9a8773aa11ee7c6951ca3acc60cbaa
ms.sourcegitcommit: 8becfb03eb60ba205c670a634ff4daa8071bcd06
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 10/31/2019
ms.locfileid: "73230479"
